alias: Katze erkannt
description: ""
mode: single
triggers:
  - webhook_id: "INSERT_WEBHOOK_ID_HERE"
    allowed_methods:
      - POST
      - PUT
    local_only: true
    trigger: webhook
conditions:
  - condition: and
    conditions:
      - condition: not
        conditions:
          - condition: template
            value_template: "{{ states('input_text.shice_letzter_tag') == trigger.data.label }}"
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.data.label == \"cami\" }}"
              - condition: state
                entity_id: input_boolean.shice_tag1_aktiv
                state: "on"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.data.label == \"flausch\" }}"
              - condition: state
                entity_id: input_boolean.shice_tag2_aktiv
                state: "on"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.data.label == \"levi\" }}"
              - condition: state
                entity_id: input_boolean.shice_tag3_aktiv
                state: "on"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.data.label == \"rofl\" }}"
              - condition: state
                entity_id: input_boolean.shice_tag4_aktiv
                state: "on"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.data.label == \"Negative\" }}"
              - condition: state
                entity_id: input_boolean.shice_tag5_aktiv
                state: "on"
actions:
  - data:
      message: "{{trigger.data.label}} erkannt"
      entity_id: >-
        media_player.nestaudio2425, media_player.nestaudio0215,
        media_player.googlehome7366, media_player.schlafzimmer,
        media_player.nestmini3227
    action: tts.watson_say
  - metadata: {}
    data:
      value: "{{trigger.data.label}}"
    target:
      entity_id: input_text.shice_letzter_tag
    action: input_text.set_value
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
    enabled: true
  - data:
      message: |-
        {% if states('input_number.shice_letztes_kisterl') | int == 1 %}
          Mögliche Kakaa Deponierung bei Kisterl 1 detektiert! Ich wiederhole:
          Mögliche Kakaa Deponierung bei Kisterl 1 detektiert!
        {% elif states('input_number.shice_letztes_kisterl') | int == 2 %}
          Ein Mitarbeiter der Stuhlabteilung wird gebeten zu Kisterl 2 zu kommen!
        {% elif states('input_number.shice_letztes_kisterl') | int == 3 %}
          Die Kacke ist am dampfen - möglicherweise. In Kisterl 3.
        {% endif %}
      entity_id: >-
        media_player.nestaudio2425, media_player.nestaudio0215,
        media_player.googlehome7366, media_player.schlafzimmer,
        media_player.nestmini3227
    action: tts.watson_say

