alias: Kisterl 1 aktivierung
description: ""
mode: single
triggers:
  - webhook_id: "INSERT_WEBHOOK_ID_HERE"
    allowed_methods:
      - POST
      - PUT
      - GET
    local_only: true
    trigger: webhook
conditions: []
actions:
  - metadata: {}
    data:
      value: 1
    target:
      entity_id: input_number.shice_letztes_kisterl
    action: input_number.set_value
  - target:
      entity_id: timer.shice_timer
    data: {}
    action: timer.cancel
  - metadata: {}
    data: {}
    target:
      entity_id: timer.shice_timer
    action: timer.start

